inherits:
    - strictness_medium

ignore:
  - (^|/)\..+
  - ^docs/
  # user-contributed, very chaotic and unmaintainable
  - ^x84/default/extras
  # user-contributed, not necessary to pylint
  - ^x84/encodings
  # derived from mini-boa, not very well documented.
  - ^x84/telnet.py
  # this code is disgusting, please don't view it.
  - ^x84/default/tetris.py

test-warnings: true

output-format: grouped

dodgy:
    # Looks at Python code to search for things which look "dodgy"
    # such as passwords or git conflict artifacts
    run: true

frosted:
    # static analysis
    run: true
    disable:
        # (...) imported but unused, does not understand __all__
        - E101

mccabe:
    # complexity checking.
    run: true

pep257:
    # docstring checking
    run: true

pep8:
    # style checking
    run: true
    options:
        max-line-length: 100

pyflakes:
    # preferring 'frosted' instead (a fork of)
    run: false

pylint:
    # static analysis and then some
    run: true
    options:
        # pytest module has dynamically assigned functions,
        # raising errors such as: E1101: Module 'pytest' has
        # no 'mark' member
        ignored-classes: pytest
    disable:
        # Use % formatting in logging functions but pass the % parameters as arguments
        - W1202
        # Used builtin function 'map' (col 29)
        - W0141
        # Used * or ** magic
        - W0142
        # Cyclic import (x84.bbs -> x84.bbs.dbproxy -> x84.db -> x84.bbs.ini -> x84.ssh -> x84.sftp)
        # we really can't prevent this without a complete overhaul.
        - R0401
        # Argument 'self' passed by position and keyword in method call
        # we use this commonly for .format(self=self)
        - E1124
        # Interface not implemented
        # happens in ssh.py and sftp.py due to paramiko's old-style classes.
        - R0923

pyroma:
    # checks setup.py
    run: true

vulture:
    # this tool does a good job of finding unused code.
    run: false

# vim: noai:ts=4:sw=4
